name: visc_starter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  either_dart: ^1.0.0
  envied: ^0.5.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.2
  pull_to_refresh_flutter3: ^2.0.2
  test: ^1.24.9

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  envied_generator: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
      - assets/img/
      - assets/ca/